# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Henry Hadlow
email: henry@manofscience.co.uk
description: Henry Hadlow is a designer. He creates products, services and businesses for the internet.
baseurl: ""
url: "https://www.manofscience.co.uk"

# Build settings
markdown: kramdown
exclude: ["README.md", ".ruby-version", "Gemfile", "Gemfile.lock", "s3_website.yml"]
permalink: /:title/
